# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-11 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_priority',
            field=models.IntegerField(default=0),
        ),
    ]
