---
hosts : 
        ipadress : ['180.76.159.87','47.100.96.200','101.132.151.31']
        user : ['root','root','root']
        password : ['luohua139@','luohua139@','luohua139@']
        ownsystem : ['ific','ific','sociallife']
        syscmd_list : ["cat /etc/issue",
                        "cat /etc/redhat-release",
                        "hostname",
                        "cat /sys/class/net/[^vtlsb]*/address||esxcfg-vmknic -l|awk '{print $8}'|grep ':'",
                        "dmidecode -s system-serial-number",
                        "dmidecode -s system-manufacturer",
                        "dmidecode -s system-product-name"]